//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEFA_API_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchStats
    {
        public int Match_ID { get; set; }
        public int Home_Team_ID { get; set; }
        public int Away_Team_ID { get; set; }
        public int GoalsHomeTeam { get; set; }
        public int GoalsAwayTeam { get; set; }
        public int RedCardsHomeTeam { get; set; }
        public int YellowCardsHomeTeam { get; set; }
        public int RedCardsAwayTeam { get; set; }
        public int YellowCardsAwayTeam { get; set; }
    
        public virtual Nation Nation { get; set; }
        public virtual Nation Nation1 { get; set; }
    }
}
