//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEFA_API_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchInfo
    {
        public int Match_ID { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Stadium { get; set; }
        public Nullable<int> Nation_ID { get; set; }
    
        public virtual Nation Nation { get; set; }
    }
}
