//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UEFA_API_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int Player_ID { get; set; }
        public string PlayerName { get; set; }
        public string Team { get; set; }
        public string Position { get; set; }
        public int Nation_ID { get; set; }
    
        public virtual Nation Nation { get; set; }
    }
}
